---
title: "Expression of Emotions in 20th Century Chinese Books"
author: "Ryan Cheung"
date: "Thursday, August 15, 2014"
output:
  html_document:
    keep_md: yes
---
```{r}
library(ggplot2)
library(ggthemes)
theme_set(theme_minimal(12))
library(RColorBrewer)
```

## Load in data 读入数据
```{r}
total <- read.table("summaryout.txt", header = T)
posdf <- read.csv("posdf.csv", stringsAsFactors = F, header = T)
negdf <- read.csv("negdf.csv", stringsAsFactors = F, header = T)
```

## General Usage of Emotion Words
```{r GTrend, warning = F}
x = (rowSums(negdf[,2:101]) + rowSums(posdf[,2:101]))/total[,3]
totalScore <- as.data.frame(x)
totalScore$y <- seq(1900:2000)
ggplot(aes(x = y, y = x), data = totalScore)+
  geom_point(aes(size = 5)) +
  stat_smooth(method = "loess",
              formula = y~x,
              size = 1,
              color = 'black',
              alpha = 0.3)+
  geom_line(aes(alpha = 0.3))+
  labs(title = "情感词语总使用频次走势", x= "年份", y = "使用频次")
```


## Creating DataFrame

```{r}
df <- as.data.frame(cbind(posdf[,2:595], negdf[,2:702]))
row.names(df) <- posdf[,1]
df <- df/total[,3]
```

## Clustering

### Hierarchical Clusting
```{r HIC}
distance = dist(df, method = "euclidean")
clusterIntensity = hclust(distance, method="ward.D")
plot(clusterIntensity)
```

### Select 5 Cluster in HC
```{r HIC5, warning = F}
plot(clusterIntensity, labels = F, axes = F, xlab = "距离", ylab = "高度", main = "层次聚类系统树图", ann = T)
rect.hclust(clusterIntensity, k = 5, border = "red")
YearCluster = cutree(clusterIntensity, k = 5)
YearCluster
```

### Plot the clusters
```{r Cluster, warning = F}
Clusters <- as.data.frame(cbind(row.names(total), YearCluster))
names(Clusters) <- c('Year','Cluster')
Clusters$Cluster <- as.factor(Clusters$Cluster)
Clusters$Year <- seq(1900,2000)
ggplot(Clusters, aes(x = Year, y = Cluster, color = Cluster, size = 3)) +
  geom_point() +
  scale_color_brewer(type = 'qual',
    guide = guide_legend(title = '聚集', reverse = T,
    override.aes = list(alpha = 1, size = 5))) +
  labs(title = "聚集和所属年份", x= "年份", y = "所属聚集") +
  scale_x_continuous(breaks = seq(1900,2000,10)) +
  scale_y_discrete(breaks = NULL)
```

### Write the Clusters to File
```{r}
#write.csv(Clusters, file = "Clusters.csv", row.names = F)
```





